### PR TITLE
Parallel building, makefile clean, and build step

### PR DESCRIPTION
**Pull request by bridadan**
Here are the changes I've implemented:

- Enabled parallel building by default
- Broke up clean step into multiple calls to `rm` to avoid windows command line limit
- Fixes `build` step in exporter API
    - Had to modify what gets printed to the screen because eclipse is extremely verbose

I have concerns about the following before you merge this that we should probably address:

- I created a new `mbedclean` step in the `makefile.targets` to break up the clean step, however this requires a project file change to point at `mbedclean` instead of `clean`. Another option is just to rename `mbedclean` to `clean`. But this generates the following make warning:

```
14:22:41 **** Clean-only build of configuration Debug for project mbed-os-example-blinky ****
make -j4 clean 
../makefile.targets:7: warning: overriding recipe for target 'clean'
makefile:108: warning: ignoring old recipe for target 'clean'
```

Do you have any preference here?

### CODE REVIEW

**Comment by ilg-ul** [comment]
I think that a new target is the lesser of two evils.

what are the define/endef lines used for in the new template file?

**Comment by bridadan** [comment]
> what are the define/endef lines used for in the new template file?

Let me first preface by saying I'm a bit of a Makefile newbie so this might not be the best way to do it :smile: 

But it's used to create a new line to force each iteration of the `$(foreach ...)` to be treated as a separate command. @theotherjimmy are you aware of a nicer way of doing this?

@ilg-ul Another option could be to just delete the Debug folder right?

**Comment by ilg-ul** [comment]
>  just delete the Debug folder right

removing Debug is the definite clean, but the problem is that you should not hardcode the name, since the same should apply to Release too, and to any other configuration, if the user decides to rename them, or to add new ones.

so, considering that the make process is started in the Debug/Release/etc folder, you may try `rm -rf .`

**Comment by bridadan** [comment]
@ilg-ul Sorry for the delay on this, I promise I haven't forgotten! I've been traveling this week but I hope to return to this next week. Thanks for your patience!

**Comment by ilg-ul** [comment]
@bridadan, I decided to merge the PR as it is, since I want to make some further changes.

If necessary, we'll correct details later.

**Pull request merged**
